### ISSUE TITLE
[Request] Advantage on Hit Dice recovery

### ISSUE THREAD

**Issue by Bradeck** [roth-michael/FoundryVTT-RestRecovery#168]
**Is your feature request related to a problem? Please describe.**
I run a campaign where the survival condition will be a bit harsh, and the RAW long rest mechanic will trivialise it, and I also fintd it silly in dungeons or while exploring a dangerous area on the map.
So I want to restrict long resting in a non safe environnement (i.e. inn or home). So anywhere the PC think they must take turns to take a watch during the resting period, I wand to forbid long rest, but they can take an "extended short rest", where if they can sleep as long as in a long rest, they can throw their Hit Dice "with advantage", but won't recover spells / features that needs a long rest.

**Describe the solution you'd like**
Add a "Extended short rest" or "long rest in a hostile environment", that would function as a long rest except for :
- Don't recover full HP
- Allow hit dice rolling to recover HP, but with advantage (roll 2 dice, keep the highest)
- Don't allow recovery of feature needing a long rest

**Describe alternatives you've considered**
- Just add a check box with "roll hit dice with advantage" on short rest
The rest can be done easely manually in Foundry

**Comment by f4hy** [comment]
I am also interested in this. working on a patch to do this actually.

**Comment by roth-michael** [comment]
I've recently started going through some of these older issues. Let me know if you run into trouble implementing it and I’ll give it a go

**Comment by f4hy** [comment]
So I have something that works to pick advantage for all hit die rolls, but where the formula gets set currently https://github.com/roth-michael/FoundryVTT-RestRecovery/blob/main/scripts/rest-workflow.js#L86 affects all rolls not just short of long rest.

would be a minor refactor to be able to set these things separately for short or long rests.

**Comment by roth-michael** [comment]
This ought to be good in the latest release (1.11.0). Let me know @Bradeck if it's sufficient for you and I'll close this ticket. I'd recommend creating a new rest profile for your "Extended short rest"/"long hostile-environment rest" scenario, and then when prompting a rest for your players you can simply choose that one if necessary.

**Comment by Bradeck** [comment]
Thanks. So I tested it, but my test environement in on v12 dd3.2, so not ideal, and it may explain what happens on my end. 
1/ The ADV on roll formula works well with the custom rest profile
2/ But when as a GM I use the prompt button, no prompt appears on the player side. But if the player then use the short rest button on his character sheet, all works with the intended profile, so it's a minor inconvenience.
3/ I set the custom short rest to be 8 hour long. When as a GM I click on the prompt button, 8 hours pass. But in the chat when the player finish their short rest, it displays 1 hour only (keep in mind as they don't see the prompt, they must use the short rest button, which still use the correct formula, with adv or not, based on the selected profile when the GM tries to prompt).
![SR_Custtom01](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/47001786/0be13963-29d5-4982-b97f-bdad05285716)
![SR_Custtom02](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/47001786/e31e9537-0c24-4abd-8dd1-357d03fd9ac5)

**Comment by roth-michael** [comment]
Hm well point 3 should be easily fixable on my end, I suspect I forgot to change some hardcoded value somewhere. Re 2 can you elaborate? Does prompting rest not pop up a window for the players selected at all?

**Comment by roth-michael** [comment]
With 1.11.1 (very fun version name), the chat message flavors should be fixed to account for custom rest times. Would very much like to help you figure out your prompt issue (I'm testing on V12, dnd3.2.0 and not running into any such issue) if you're still having it.

**Comment by Bradeck** [comment]
Hi, I setup a proper test environment, And I still have the issue of the prompt not appearing. Here's a video showing it. 
[R&R.webm](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/47001786/a8060092-ca41-4c4d-a758-def16f8231f7)
On the browser I use for the player side, it's Edge, used only for foundry play, so no extension beside a password manager. I also tried with chrome, same result. I'm almost certain it's something on my end, but I'm at a loss as to what...

**Comment by Bradeck** [comment]
I knew it was basic user error as it worked before. So it's good to go for me and my use case. Thanks !

**Comment by roth-michael** [comment]
Awesome, glad it's all working!
